### ISSUE TITLE
Docfx: Build Process -- run html-proofer or similar to check for dead links

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#352]

**Comment by SeanKilleen** [comment]
#476 wasn't successful for html-proofer due to it hitting github and getting rate limited. I'd like us to be better internet citizens.

I think we can follow-up on this with another PR and perhaps ignore github issue and PR URLs. That should cut down on a ton of noise.

For what it's worth, here's the GitHub action job that worked:

```yaml
html_proofer:
    name: HTML checks (FYI only)
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download site artifacts
      uses: actions/download-artifact@v2
      with:
        name: siteArtifact
    - name: unzip site contents
      run: unzip _site.zip
    - name: Check HTML
      uses: chabad360/htmlproofer@master
      with:
        directory: "./docs/_site/articles"
        arguments: --log-level debug
```
