### ISSUE TITLE
Add external links to issue template file

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#356]
## Current Behavior

Currently, we have the text: 

```
<!-- 
This repository is for issues with NUnit documentation.
 - If you have an issue with the test framework, go to: https://github.com/nunit/nunit/issues/new
 - If you have an issue with the console runner, go to: https://github.com/nunit/nunit-console/issues/new
 - If you have an issue with the VSTest adapter, go to: https://github.com/nunit/nunit3-vs-adapter/issues/new
 - If you have an issue with another component, go to: https://github.com/nunit#org-repositories
-->
```

## Suggested Change

Move the external links into an issue template file in `.github/ISSUE_TEMPLATE/config.yml`, such as:

```yml
blank_issues_enabled: true
contact_links:
  - name: Test Framework Issue
    url: https://github.com/nunit/nunit/issues/new
    about: For issues encountered when using the test framework
  - name: Console Runner Issue
    url: https://github.com/nunit/nunit-console/issues/new
    about: For issues encountered when using the console runner
  - name: VS Test Adapter
    url: https://github.com/nunit/nunit3-vs-adapter/issues/new
    about: For issues encountered when using the NUnit Visual Studio Test Adapter
  - name: Issue while using another NUnit project / component
    url: https://github.com/nunit#org-repositories
    about: Please find the appropriate repository at this list and file an issue there.
```
