### ISSUE TITLE
Add warning banner to legacy documentation

### ISSUE THREAD

**Issue by rprouse** [nunit/docs#96]
On the nunit.org website, we should add a banner at the top of every documentation page pre-2.6.4 that states that there is newer documentation and link to the 2.6.4 and 3.x documentation.

The legacy docs are PHP on the website, so it should just be a matter of inspecting the version variable that is passed in for the legacy docs.

**Comment by CharliePoole** [comment]
@rprouse I assigned this to myself since I'm already working on it. Let's resolve how to handle website issues in the future... I don't feel they belong here since any contributor has access to fix an nunit/docs issue, but nunit/nunit.org issues can only be fixed by a few people without forking...

**Comment by CharliePoole** [comment]
@rprouse @MgSam 
I added a banner to the website - please review before I close this.

**Comment by rprouse** [comment]
Should we make the notice a bit more obvious? If people are missing the version in the right menu, they may miss that text. If we update the CSS to,

```css
div.notice {
    text-align: center;
    font-style: italic;
    font-weight: bold;
    border: 1px solid goldenrod;
    margin: 38px 0 0 50px;
    padding: 12px;
    background-color: #FEEFB3;
    color: #9F6000;
    width: 60%;
    max-width: 660px;
}
```

It will look like this,

![image](https://cloud.githubusercontent.com/assets/493828/17389596/b3a4c2a2-59d3-11e6-95e4-9aea0b4daba3.png)
